[workspace]
resolver = "2"
members = ["crates/*"]

# [package]
# name = "graphity"
# version = "0.0.1"
# edition = "2021"
# license = "MIT"

[workspace.dependencies]
indexmap = "2.2.1"
miette = "5.10.0"
once_cell = "1.19.0"
petgraph = { version = "0.6.4", default-features = false, features = [
	"serde-1",
] }
regex = "1.10.3"
rustc-hash = "1.1.0"
semver = "1.0.21"
serde = "1.0.195"
serde_json = "1.0.111"
serde_yaml = "0.9.30"
starbase_sandbox = "0.3.0"
starbase_utils = { version = "0.4.0", default-features = false, features = [
	"miette",
] }
thiserror = "1.0.56"
